### model
model_name_or_path: models/gemma-3-270m-it

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 32
lora_alpha: 64
lora_dropout: 0.05
lora_target: all

### dataset
dataset_dir: data/v3-4-0-74a63ca3
dataset: action_sequence_sft_train
eval_dataset: action_sequence_sft_validation_1k
template: gemma2
cutoff_len: 4096
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/gemma3-270m/lora/sft_v340
logging_steps: 10
save_strategy: steps
save_steps: 500
save_total_limit: 3
plot_loss: true
overwrite_output_dir: false
save_only_model: false
report_to: none

### training
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### evaluation
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 500
